export const GET_LOGINSTATUS = 'GET_LOGINSTATUS';
export const GET_ISWECHAT = 'GET_ISWECHAT';
export const GET_INDEX_LIST = 'GET_INDEX_LIST';
export const GET_WAITING_LIST = 'GET_WAITING_LIST';
export const GET_GROUPING_LIST = 'GET_GROUPING_LIST';

