# 对象

person: {key1: value1, key2: value2}

key:
  child-key: value
  child-key2: value2

# 复杂对象
?
  - complexkey1
  - complexkey2
:
  - complexvalue1
  - complexvalue2



# 数组
fuites:
  - 'apple'
  - 'oringe'
  - 'ganzhe'

count: [1,2,3,4,5]

# companies: [{id: 1,name: company1,price: 200W},{id: 2,name: company2,price: 500W}]
companies:
  -
    id: 1
    name: 'lisi'
    price: 200w
  -
    id: 2
    name: 'ggsi'
    price: 300w



# 纯量 纯量是最基本的，不可再分的值，包括：字符串、布尔值、整数、浮点数、Null、时间、日期
boolean:
  - TRUE # true,True 都可以
  - FALSE # false,False
float:
  - 3.14
  - 6.8523015e+5  #可以使用科学计数法
int:
  - 123
  - 0b1010_0111_0100_1010_1110    #二进制表示
null:
  nodeName:'node'
  parent:~ # 使用~表示null
string:
  - 哈哈
  - 'HELLOW WORLD'
  - newline
    newline2   # 字符串可以拆成多行，每一行会被转化成一个空格
date:
  - 2018-02-17 #日期必须使用ISO 8601格式，即yyyy-MM-dd
datetime:
  - 2018-02-17T15:02:31+08:00  #时间使用ISO 8601格式，时间和日期之间使用T连接，最后使用+代表时区



# 引用 &锚点和*别名，可以用来引用
defaults: &defaults
  adapter: postgres
  host: localhost

development:
  database: myapp_development
  <<: *defaults

test:
  database: myapp_test
  <<: *defaults

# 相当于
defaults:
  adapter: postgres
  host: localhost

development:
  database: myapp_development
  adapter:  postgres
  host:     localhost

test:
  database: myapp_test
  adapter:  postgres
  host:     localhost