//Splash
export const SPLASH_ADD_COUNT = 'SPLASH_ADD_COUNT';

// SignIn
export const SIGNIN_SET_MODLE = 'SIGNIN_SET_MODLE';
export const SIGNIN_INPUT_PHONE = 'SIGNIN_INPUT_PHONE';
export const SIGNIN_INPUT_PASSWORD = 'SIGNIN_INPUT_PASSWORD';
export const SIGNIN_INPUT_CODE = 'SIGNIN_INPUT_CODE';
export const SIGNIN_SET_CODEBUTTON = 'SIGNIN_SET_CODEBUTTON';
export const SIGNIN_SET_TEMPTOKEN = 'SIGNIN_SET_TEMPTOKEN';
export const SIGNIN_CLEAR = 'SIGNIN_CLEAR';

//Register
export const REGISTER_INPUT_PHONE = 'REGISTER_INPUT_PHONE';
export const REGISTER_INPUT_SMSC = 'REGISTER_INPUT_SMSC';
export const REGISTER_INPUT_ACCOUNT = 'REGISTER_INPUT_ACCOUNT';
export const REGISTER_INPUT_PASSWORD = 'REGISTER_INPUT_PASSWORD';
export const REGISTER_INPUT_REPASSWORD = 'REGISTER_INPUT_REPASSWORD';
export const REGISTER_SET_TEMPTOKEN = 'REGISTER_SET_TEMPTOKEN';
export const REGISTER_SET_CODEBUTTON = 'REGISTER_SET_CODEBUTTON';
export const REGISTER_SET_AGREEPROTOCOL = 'REGISTER_SET_AGREEPROTOCOL';
export const REGISTER_CLEAR = 'REGISTER_CLEAR';

// SafeSetting
export const SAFE_EDIT_PHONE = 'SAFE_EDIT_PHONE';
export const SAFE_GET_SMSCODE = 'SAFE_GET_SMSCODE';
export const SAFE_SET_CODEBUTTON = 'SAFE_SET_CODEBUTTON';
export const SAFE_CLEAR = 'SAFE_CLEAR';

// UserInfo
export const USERINFO_UPGRADE_USERTOKEN = 'USERINFO_UPGRADE_USERTOKEN';

// FindPassword
export const FIND_INPUT_PHONE = 'FIND_INPUT_PHONE';
export const FIND_INPUT_CODE = 'FIND_INPUT_CODE';
export const FIND_INPUT_PASSWORD = 'FIND_INPUT_PASSWORD';
export const FIND_INPUT_SECOND_PASSWORD = 'FIND_INPUT_SECOND_PASSWORD';
export const FIND_SET_CODEBUTTON = 'FIND_SET_CODEBUTTON';
export const FIND_SET_TOKEN = 'FIND_SET_TOKEN';
export const FIND_SHOW_PASSWORD_DIV = 'FIND_SHOW_PASSWORD_DIV';
export const FIND_CLEAR = 'FIND_CLEAR';

//RegisterInfo
export const REGISTERINFO_INPUT_ACCOUNT = 'REGISTERINFO_INPUT_ACCOUNT';
export const REGISTERINFO_INPUT_PASSWORD = 'REGISTERINFO_INPUT_PASSWORD';
export const REGISTERINFO_INPUT_REPASSWORD = 'REGISTERINFO_INPUT_REPASSWORD';

//----------------------------MerMine----------------------------------
export const MERMINE_ADD_INFO = 'MERMINE_ADD_INFO';
export const MERMINE_UNCHECKED_PERSON = 'MERMINE_UNCHECKED_PERSON';
export const MERMINE_INFO_CLEAR = 'MERMINE_INFO_CLEAR';

// PointDetail
export const MER_POINT_DETAIL_PULLDOWN = 'MER_POINT_DETAIL_PULLDOWN';
export const MER_POINT_DETAIL_PULLUP = 'MER_POINT_DETAIL_PULLUP';
export const MER_POINT_DETAIL_GET_INFO = 'MER_POINT_DETAIL_GET_INFO';
export const MER_POINT_DETAIL_CLEAR = 'MER_POINT_DETAIL_CLEAR';

// MerStaff
export const MER_STAFF_GET_ALL_LIST = 'MER_STAFF_GET_ALL_LIST';
export const MER_STAFF_GET_CHECK_LIST = 'MER_STAFF_GET_CHECK_LIST';
export const MER_STAFF_GET_AUDITED_LIST = 'MER_STAFF_GET_AUDITED_LIST';
export const MER_STAFF_PULLDROP_REFRESH = 'MER_STAFF_PULLDROP_REFRESH';
export const MER_STAFF_PULLUP_REFRESH = 'MER_STAFF_PULLUP_REFRESH';
export const MER_STAFF_VERIFY_POPUP_SHOW = 'MER_STAFF_VERIFY_POPUP_SHOW';
export const MER_STAFF_IDENTITY_VALUE = 'MER_STAFF_IDENTITY_VALUE';
export const MER_STAFF_FIXDEL_SHOW = 'MER_STAFF_FIXDEL_SHOW';
export const MER_STAFF_NAV_INDEX = 'MER_STAFF_NAV_INDEX';
export const MER_STAFF_SET_CHECKBOX_ALL = 'MER_STAFF_SET_CHECKBOX_ALL';
export const MER_STAFF_SET_All_CHECKBOX = 'MER_STAFF_SET_All_CHECKBOX';
export const MER_STAFF_SET_WAIT_CHECKBOX = 'MER_STAFF_SET_WAIT_CHECKBOX';
export const MER_STAFF_SET_FINSH_CHECKBOX = 'MER_STAFF_SET_FINSH_CHECKBOX';
export const MER_STAFF_UNCHECK_PERSON = 'MER_STAFF_UNCHECK_PERSON';
export const MER_STAFF_CLEAR = 'MER_STAFF_CLEAR';

// MerInformation
export const MERINFORMATION_GET_LIST = 'MERINFORMATION_GET_LIST';
export const MERINFORMATION_REQUEST_TYPE = 'MERINFORMATION_REQUEST_TYPE';
export const MERINFORMATION_CLEAR = 'MERINFORMATION_CLEAR';

// MerchantCA
export const MERCHANTCA_GET_INFO = 'MERCHANTCA_GET_INFO';
export const MERCHANTCA_INPUT_STORE_NAME = 'MERCHANTCA_INPUT_STORE_NAME';
export const MERCHANTCA_INPUT_STORE_TEL = 'MERCHANTCA_INPUT_STORE_TEL';
export const MERCHANTCA_INPUT_STORE_ADDRESS = 'MERCHANTCA_INPUT_STORE_ADDRESS';
export const MERCHANTCA_INPUT_CONTACT_NAME = 'MERCHANTCA_INPUT_CONTACT_NAME';
export const MERCHANTCA_INPUT_CELL_PHONE = 'MERCHANTCA_INPUT_CELL_PHONE';
export const MERCHANTCA_INPUT_TELEPHONE = 'MERCHANTCA_INPUT_TELEPHONE';
export const MERCHANTCA_INPUT_MAILBOX = 'MERCHANTCA_INPUT_MAILBOX';
export const MERCHANTCA_INPUT_CONTACT_ADDRESS = 'MERCHANTCA_INPUT_CONTACT_ADDRESS';
export const MERCHANTCA_BUSINESS_LICENSE = 'MERCHANTCA_BUSINESS_LICENSE';
export const MERCHANTCA_LICENSE_STATE = 'MERCHANTCA_LICENSE_STATE';
export const MERCHANTCA_CLEAR = 'MERCHANTCA_CLEAR';

// MerHome
export const MERHOME_GET_INFO = 'HOME_GET_INFO';
export const MERHOME_INFO_CLEAR = 'MERHOME_INFO_CLEAR';

// MerCouponRecycle
export const MER_COUPON_RECYCLE_INPUT_RECYCLEID = 'MER_COUPON_RECYCLE_INPUT_RECYCLEID';
export const MER_COUPON_RECYCLE_CLEAR = 'MER_COUPON_RECYCLE_CLEAR';

// MerShopinfo
export const MER_SHOP_INFO_GET = 'MER_SHOP_INFO_GET';
export const MER_SHOP_IS_OPEN = 'MER_SHOP_IS_OPEN';
export const MER_SHOP_INFO_CLEAR = 'MER_SHOP_INFO_CLEAR';

// MerEditShop
export const MER_EDIT_SHOP_NAME = 'MER_EDIT_SHOP_NAME';
export const MER_EDIT_SHOP_CLEAR = 'MER_EDIT_SHOP_CLEAR';
export const MER_EDIT_SHOP_TEL = 'MER_EDIT_SHOP_TEL';
export const MER_EDIT_SHOP_GET_SMSCODE = 'MER_EDIT_SHOP_GET_SMSCODE';
export const MER_EDIT_SHOP_SET_CODEBUTTON = 'MER_EDIT_SHOP_SET_CODEBUTTON';
export const MER_EDIT_SHOP_ADDRESS_NAME = 'MER_EDIT_SHOP_ADDRESS_NAME';
export const MER_EDIT_SHOP_ADDRESS_AREA = 'MER_EDIT_SHOP_ADDRESS_AREA';
export const MER_EDIT_SHOP_OLD_TEL = 'MER_EDIT_SHOP_OLD_TEL';
export const MER_EDIT_SHOP_OLD_SMSCODE = 'MER_EDIT_SHOP_OLD_SMSCODE';
export const MER_EDIT_SHOP_BIND_PHONE = 'MER_EDIT_SHOP_BIND_PHONE';
export const MER_EDIT_SHOP_ADDRESS_CODE = 'MER_EDIT_SHOP_ADDRESS_CODE';
export const MER_EDIT_SHOP_INPUT_SHOP_DETAIL = 'MER_EDIT_SHOP_INPUT_SHOP_DETAIL';


